spring:
  application:
    name: likelion-spring

  datasource:
    url: jdbc:mysql://likelion-database.cj0eiem4o908.ap-northeast-2.rds.amazonaws.com
    username: likelion
    password: likelion0000
